name = "crowntag"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[[durable_objects.bindings]]
name = "ARENA"
class_name = "Arena"

[[durable_objects.bindings]]
name = "MATCHMAKER"
class_name = "Matchmaker"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Arena", "Matchmaker"]

[assets]
directory = "../client/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"

[dev]
port = 8787
